### ISSUE TITLE
Provide a way to check missing environment and keys via rake task

### ISSUE THREAD

**Issue by vraravam** [theleoborges/app_constants#3]
Wouldn't it be good if there was a rake task to verify that all keys are present before starting the app server or before/during deployment?

We did this at the big webhosting client around 3+ years ago. Please ping me at vraravam -at- thoughtworks -dot- com in case you are interested. I can help implement this. (I did the exact same functionality along with that rake task there - but it could not be open sourced).

**Comment by theleoborges** [comment]
Hey,

I haven't needed it myself but it sounds like it would be useful to some. Feel free to come up with an implementation for this. I'd be happy to merge :)

Cheers
